# Generated by Django 4.1.3 on 2022-11-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity_donation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.TextField(choices=[('Fundacja', 'Fundacja'), ('Organizacja pozarządowa', 'Organizacja pozarządowa'), ('Lokalna zbiórka', 'Lokalna Zbiórka')], default='Foundation'),
        ),
    ]
